name: scroll_time_picker
description: "A Customizable Time Picker Widget for Flutter"
version: 1.1.1
homepage: https://github.com/azisanw19/flutter-scroll-time-picker

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: